# Generated by Django 4.2.4 on 2023-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, null=True)),
                ('phone', models.CharField(max_length=191)),
                ('uuid', models.CharField(max_length=36, null=True)),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to='avatars/')),
                ('ball', models.IntegerField(default=0)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.BooleanField(default=True)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=32, null=True)),
                ('lng', models.DecimalField(decimal_places=16, max_digits=32, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fcm_token', models.CharField(max_length=191, null=True)),
                ('last_updated_personal_at', models.DateTimeField(null=True)),
                ('points_per_visit', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('ip_address', models.CharField(max_length=45, null=True)),
                ('device_type', models.CharField(max_length=191, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
